before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/samzong/gmc/cmd.Version={{.Version}} -X github.com/samzong/gmc/cmd.BuildTime={{.Date}}
    binary: gmc

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ if .Env.IMAGE_REGISTRY_OWNER }}{{ .Env.IMAGE_REGISTRY_OWNER }}{{ else }}samzong{{ end }}/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/{{ if .Env.IMAGE_REGISTRY_OWNER }}{{ .Env.IMAGE_REGISTRY_OWNER }}{{ else }}samzong{{ end }}/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile.goreleaser
    skip_push: false
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/{{ if .Env.IMAGE_REGISTRY_OWNER }}{{ .Env.IMAGE_REGISTRY_OWNER }}{{ else }}samzong{{ end }}/{{ .ProjectName }}:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.goreleaser
    skip_push: false
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}" 