# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - mkdir -p docs/man
    - go run cmd/gendoc/main.go

builds:
  - id: gmc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/samzong/gmc/cmd.Version={{.Version}} -X github.com/samzong/gmc/cmd.BuildTime={{.Date}}
    binary: gmc

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - docs/man/*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

dockers_v2:
  - ids:
      - gmc
    images:
      - "ghcr.io/{{ if .Env.IMAGE_REGISTRY_OWNER }}{{ .Env.IMAGE_REGISTRY_OWNER }}{{ else }}samzong{{ end }}/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - latest
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64
    disable: "{{ .IsSnapshot }}"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
