FROM alpine:3.19

ARG TARGETPLATFORM

RUN apk --no-cache add ca-certificates git

WORKDIR /root

# Copy the platform-specific binary from goreleaser build context
COPY ${TARGETPLATFORM}/gmc /usr/local/bin/gmc

# Make sure gmc is executable
RUN chmod +x /usr/local/bin/gmc

# Set the entrypoint
ENTRYPOINT ["gmc"]
CMD ["--help"]

